### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by davidbeig** [Platoniq/platoniq.net#30]
When trying to build the docker image for the first time it breaks.

Due to the gem update, the system tries to install the latest version of rubygems, which [does not support ruby 2.7
](https://github.com/rubygems/rubygems/releases/tag/v3.5.0)

```
RUN gem update --system
```
This can be fixes by not updating the gem system itself. Where you trying to update all preinstalled gems or the rubygems itself?

After this change, we can make sure to have a compatible bundler version, the last one for ruby 2.7 is bundler 2.4.22.

```
RUN gem install bundler -v 2.4.22
```

After that we can see another problem with the sass-embedded gem.

```
  gem "sass-embedded", "~> 1.63.6"
```

After that, there are some syntax errors in the markdown files. Such as accents in title or a syntax error in a json object in one of the jekyll plugins. I think that it might be why the deployment has not been working for the past couple of weeks.

Thanks!

**Comment by rafaelpoza** [comment]
We've fixed the Dockerfile from your comment with the following steps:

- We've made sure the origin is the one we use in the final environment using ruby 2.72 and forcing the platform to linux/adm64 (this can solve son issues in new Apple's SoCs)

- After that, to make sure the gem "sass-embedded" were well installed, we need rubygems working with version 3.3.22. This version is installed "manually" in the Dockerfile 

- We keep the version 2.4.22 in bundler as you mention


Once done these changes, the project is working fine :)

**Comment by davidbeig** [comment]
Thanks, i will close this issue then :)
